// @ts-nocheck
"use client";

import React, { useEffect } from "react";

export default function Page() {
  useEffect(() => {
    const runScript = () => {
      try {
        // Draw edges between nodes dynamically
        function drawEdges() {
          const svg = document.getElementById("graph-edges");
          const layer = document.getElementById("nodes-layer");
          if (!svg || !layer) return;
          
          const container = layer.getBoundingClientRect();
          
          svg.innerHTML = `
            <defs>
              <filter id="soft-glow" x="-10%" y="-10%" width="120%" height="120%">
                <feGaussianBlur stdDeviation="2" result="blur"/>
                <feMerge>
                  <feMergeNode in="blur"/>
                  <feMergeNode in="SourceGraphic"/>
                </feMerge>
              </filter>
            </defs>
          `;

          const connections = [
            ["node-1", "node-2"],
            ["node-2", "node-3"],
            ["node-3", "node-4"],
            ["node-4", "node-5"],
            ["node-1", "node-4"],
          ];

          connections.forEach(([fromId, toId]) => {
            const fromEl = document.querySelector(`[data-id="${fromId}"]`);
            const toEl = document.querySelector(`[data-id="${toId}"]`);
            if (!fromEl || !toEl) return;

            const fromNode = fromEl.getBoundingClientRect();
            const toNode = toEl.getBoundingClientRect();

            const x1 = fromNode.left + fromNode.width / 2 - container.left;
            const y1 = fromNode.top + fromNode.height / 2 - container.top;
            const x2 = toNode.left + toNode.width / 2 - container.left;
            const y2 = toNode.top + toNode.height / 2 - container.top;

            const path = document.createElementNS("http://www.w3.org/2000/svg", "path");
            const midX = (x1 + x2) / 2;
            const d = `M ${x1} ${y1} C ${midX} ${y1}, ${midX} ${y2}, ${x2} ${y2}`;

            path.setAttribute("d", d);
            path.setAttribute("stroke", "hsl(var(--primary))");
            path.setAttribute("stroke-width", "1.5");
            path.setAttribute("fill", "none");
            path.setAttribute("class", "neon-line opacity-40");
            path.setAttribute("filter", "url(#soft-glow)");

            svg.appendChild(path);
          });
        }

        // Run after component mounts and DOM updates
        setTimeout(drawEdges, 100);

        window.addEventListener("resize", drawEdges);

        return () => {
          window.removeEventListener("resize", drawEdges);
        };
      } catch (e) {
        console.error("Error running page script:", e);
      }
    };
    return runScript();
  }, []);

  return (
    <>
      <style dangerouslySetInnerHTML={{ __html: `
        .neon-line {
          stroke-dasharray: 12;
          animation: dash 30s linear infinite;
        }

        @keyframes dash {
          to { stroke-dashoffset: -1000; }
        }

        .material-symbols-outlined {
          font-variation-settings: 'FILL' 0, 'wght' 400, 'GRAD' 0, 'opsz' 24;
          vertical-align: middle;
        }
      ` }} />

      <div className="max-w-7xl mx-auto space-y-8">
        
        {/* Header Section */}
        <div className="space-y-1">
          <h1 className="text-3xl md:text-4xl font-bold text-foreground">
            Knowledge Graph
          </h1>
          <p className="text-muted-foreground text-sm max-w-xl">
            Explore causal linkages and propagation pathways generated by CityLearn's neural mapping engine.
          </p>
        </div>

        {/* Responsive Grid: Left (Graph Viewport), Right (Metadata Details) */}
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
          
          {/* Graph Viewport (8 Columns) */}
          <div className="lg:col-span-8 flex flex-col space-y-4">
            <div 
              id="graph-container"
              className="bg-slate-50 border border-border shadow-sm rounded-2xl h-[550px] relative overflow-hidden"
            >
              {/* Background grid pattern for a mapping canvas aesthetic */}
              <div className="absolute inset-0 opacity-[0.03] pointer-events-none bg-[radial-gradient(#000_1px,transparent_1px)] [background-size:16px_16px]"></div>
              
              {/* Node Connections SVG */}
              <svg className="absolute inset-0 w-full h-full pointer-events-none" id="graph-edges"></svg>
              
              {/* Nodes Layer */}
              <div className="relative w-full h-full p-8" id="nodes-layer" style={{ transition: 'transform 0.1s ease-out' }}>
                
                {/* Node 1: Summer Festival */}
                <div className="absolute top-[10%] left-[5%] node group" data-id="node-1">
                  <div className="bg-white border border-border p-4 rounded-xl shadow-sm hover:shadow-md hover:border-primary/40 transition-all w-48 cursor-pointer">
                    <div className="flex items-center justify-between mb-3">
                      <span className="material-symbols-outlined text-primary text-2xl">festival</span>
                      <span className="px-1.5 py-0.5 bg-primary/10 text-[9px] font-bold text-primary rounded">ROOT</span>
                    </div>
                    <h4 className="text-xs font-bold text-foreground truncate">Summer Festival</h4>
                    <p className="text-[10px] text-muted-foreground font-mono mt-1">EV-8892-C</p>
                  </div>
                </div>

                {/* Node 2: Road Closure */}
                <div className="absolute top-[12%] left-[50%] node group" data-id="node-2">
                  <div className="bg-white border border-border p-4 rounded-xl shadow-sm hover:shadow-md hover:border-secondary/40 transition-all w-48 cursor-pointer">
                    <div className="flex items-center justify-between mb-3">
                      <span className="material-symbols-outlined text-secondary text-2xl">block</span>
                      <span className="px-1.5 py-0.5 bg-secondary/10 text-[9px] font-bold text-secondary rounded">CAUSE</span>
                    </div>
                    <h4 className="text-xs font-bold text-foreground truncate">Main St. Closure</h4>
                    <p className="text-[10px] text-muted-foreground font-mono mt-1">Radius: 2.4km</p>
                  </div>
                </div>

                {/* Node 3: Gridlock Cascade */}
                <div className="absolute top-[45%] left-[55%] node group" data-id="node-3">
                  <div className="bg-white border border-border p-4 rounded-xl shadow-sm hover:shadow-md hover:border-amber-400/55 transition-all w-48 cursor-pointer">
                    <div className="flex items-center justify-between mb-3">
                      <span className="material-symbols-outlined text-amber-500 text-2xl">traffic</span>
                      <span className="px-1.5 py-0.5 bg-amber-50 text-[9px] font-bold text-amber-700 rounded border border-amber-100">IMPACT</span>
                    </div>
                    <h4 className="text-xs font-bold text-foreground truncate">Gridlock Cascade</h4>
                    <p className="text-[10px] text-amber-600 font-bold mt-1 uppercase text-[9px]">Severity: Critical</p>
                  </div>
                </div>

                {/* Node 4: Neural Rerouting */}
                <div className="absolute top-[60%] left-[12%] node group" data-id="node-4">
                  <div className="bg-white border border-border p-4 rounded-xl shadow-sm hover:shadow-md hover:border-primary/40 transition-all w-48 cursor-pointer">
                    <div className="flex items-center justify-between mb-3">
                      <span className="material-symbols-outlined text-primary text-2xl">route</span>
                      <span className="px-1.5 py-0.5 bg-primary/10 text-[9px] font-bold text-primary rounded">STRATEGY</span>
                    </div>
                    <h4 className="text-xs font-bold text-foreground truncate">Neural Rerouting</h4>
                    <p className="text-[10px] text-muted-foreground font-mono mt-1">Confidence: 94%</p>
                  </div>
                </div>

                {/* Node 5: Outcome */}
                <div className="absolute top-[70%] left-[50%] node group" data-id="node-5">
                  <div className="bg-white border border-primary/30 p-4 rounded-xl shadow-sm hover:shadow-md hover:border-primary transition-all w-48 cursor-pointer ring-1 ring-primary/10">
                    <div className="flex items-center justify-between mb-3">
                      <span className="material-symbols-outlined text-primary text-2xl">task_alt</span>
                      <span className="px-1.5 py-0.5 bg-primary/10 text-[9px] font-bold text-primary rounded">OUTCOME</span>
                    </div>
                    <h4 className="text-xs font-bold text-foreground truncate">Latency Reduced</h4>
                    <p className="text-[10px] text-green-600 font-bold mt-1">Δ Efficiency: +18%</p>
                  </div>
                </div>

              </div>
            </div>

            {/* Floating Control Bar */}
            <div className="flex items-center justify-center">
              <div className="flex items-center gap-2 p-2 bg-white/95 backdrop-blur-md border border-border rounded-full shadow-sm z-10">
                <button className="w-9 h-9 flex items-center justify-center rounded-full hover:bg-slate-100 text-foreground transition-colors">
                  <span className="material-symbols-outlined text-lg">zoom_in</span>
                </button>
                <button className="w-9 h-9 flex items-center justify-center rounded-full hover:bg-slate-100 text-foreground transition-colors">
                  <span className="material-symbols-outlined text-lg">zoom_out</span>
                </button>
                <div className="w-px h-5 bg-border mx-1"></div>
                <button className="w-9 h-9 flex items-center justify-center rounded-full hover:bg-slate-100 text-foreground transition-colors">
                  <span className="material-symbols-outlined text-lg">filter_center_focus</span>
                </button>
                <button className="px-4 py-2 bg-primary hover:bg-primary/95 text-white font-semibold rounded-full text-xs hover:shadow transition-all flex items-center gap-1.5">
                  <span className="material-symbols-outlined text-sm">play_arrow</span> Run Simulation
                </button>
              </div>
            </div>

          </div>

          {/* Metadata Sidebar Panel (4 Columns) */}
          <div className="lg:col-span-4">
            <div className="bg-white border border-border shadow-sm rounded-2xl p-6 flex flex-col justify-between h-full space-y-6">
              
              <div className="space-y-6">
                <div className="border-b border-border pb-4">
                  <h3 className="text-lg font-bold text-foreground flex items-center gap-2">
                    <span className="material-symbols-outlined text-primary text-xl">database</span>
                    Node Metadata
                  </h3>
                  <p className="text-[10px] text-muted-foreground font-mono mt-1">Selected: OBJECT_774</p>
                </div>

                {/* Details Section */}
                <div className="space-y-4">
                  <h4 className="text-[10px] font-bold text-muted-foreground uppercase tracking-wider">Causality Analysis</h4>
                  
                  <div className="p-4 bg-slate-50 border border-border rounded-xl space-y-2">
                    <p className="text-[10px] font-semibold text-muted-foreground">Impact Probability</p>
                    <div className="flex items-center gap-3">
                      <div className="flex-1 h-1.5 bg-slate-200 rounded-full overflow-hidden">
                        <div className="h-full bg-primary rounded-full" style={{ width: "85%" }}></div>
                      </div>
                      <span className="font-mono text-xs font-bold text-primary">85%</span>
                    </div>
                  </div>

                  <div className="p-4 bg-slate-50 border border-border rounded-xl space-y-2">
                    <p className="text-[10px] font-semibold text-muted-foreground">Propagation Delay</p>
                    <div className="flex items-center gap-3">
                      <div className="flex-1 h-1.5 bg-slate-200 rounded-full overflow-hidden">
                        <div className="h-full bg-secondary rounded-full" style={{ width: "42%" }}></div>
                      </div>
                      <span className="font-mono text-xs font-bold text-secondary">12ms</span>
                    </div>
                  </div>
                </div>

                {/* Interconnected Hubs */}
                <div className="space-y-3">
                  <h4 className="text-[10px] font-bold text-muted-foreground uppercase tracking-wider">Interconnected Hubs</h4>
                  <div className="grid grid-cols-2 gap-2">
                    <div className="bg-slate-50 border border-border p-3 rounded-lg flex flex-col items-center justify-center text-center">
                      <span className="material-symbols-outlined text-primary mb-1 text-xl">subway</span>
                      <span className="text-[10px] font-bold text-foreground">Transit</span>
                    </div>
                    <div className="bg-slate-50 border border-border p-3 rounded-lg flex flex-col items-center justify-center text-center">
                      <span className="material-symbols-outlined text-secondary mb-1 text-xl">emergency</span>
                      <span className="text-[10px] font-bold text-foreground">EMS</span>
                    </div>
                    <div className="bg-slate-50 border border-border p-3 rounded-lg flex flex-col items-center justify-center text-center">
                      <span className="material-symbols-outlined text-amber-500 mb-1 text-xl">local_police</span>
                      <span className="text-[10px] font-bold text-foreground">Patrol</span>
                    </div>
                    <div className="bg-slate-50 border border-border p-3 rounded-lg flex flex-col items-center justify-center text-center opacity-65">
                      <span className="material-symbols-outlined text-muted-foreground mb-1 text-xl">visibility_off</span>
                      <span className="text-[10px] font-bold text-foreground">Hidden</span>
                    </div>
                  </div>
                </div>

                {/* Neural Trace timeline */}
                <div className="space-y-3">
                  <h4 className="text-[10px] font-bold text-muted-foreground uppercase tracking-wider">Neural Trace</h4>
                  <div className="relative pl-4 space-y-4 before:content-[''] before:absolute before:left-1.5 before:top-1 before:bottom-1 before:w-px before:bg-slate-200">
                    
                    <div className="relative">
                      <div className="absolute -left-[14px] top-1 w-2.5 h-2.5 rounded-full bg-primary ring-4 ring-white"></div>
                      <p className="text-xs font-bold text-foreground">Event Ingested</p>
                      <p className="text-[10px] text-muted-foreground">Today at 14:22:01</p>
                    </div>

                    <div className="relative">
                      <div className="absolute -left-[14px] top-1 w-2.5 h-2.5 rounded-full bg-secondary ring-4 ring-white"></div>
                      <p className="text-xs font-bold text-foreground">Causality Mapping</p>
                      <p className="text-[10px] text-muted-foreground">Today at 14:22:05</p>
                    </div>

                    <div className="relative">
                      <div className="absolute -left-[14px] top-1 w-2.5 h-2.5 rounded-full bg-amber-500 ring-4 ring-white"></div>
                      <p className="text-xs font-bold text-foreground">Predictive Logic Run</p>
                      <p className="text-[10px] text-muted-foreground">Today at 14:22:12</p>
                    </div>

                  </div>
                </div>
              </div>

              <button className="w-full py-3 bg-transparent border border-border hover:bg-slate-50 text-muted-foreground hover:text-foreground rounded-xl text-xs font-bold uppercase tracking-wider transition-all flex items-center justify-center gap-1.5">
                <span className="material-symbols-outlined text-sm">download</span> Export Graph Data
              </button>

            </div>
          </div>

        </div>

      </div>
    </>
  );
}
